//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlashCards.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FlashCards.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string add_deck {
            get {
                return ResourceManager.GetString("add_deck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string add_flip_card {
            get {
                return ResourceManager.GetString("add_flip_card", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO &apos;flipcardknowledge&apos; (&apos;ID_User&apos;, &apos;ID_FlipCard&apos;, &apos;Knowledge&apos;) VALUES.
        /// </summary>
        internal static string add_flip_card_knowledge {
            get {
                return ResourceManager.GetString("add_flip_card_knowledge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO `users` (`Name`, `Surname`) VALUES.
        /// </summary>
        internal static string add_user {
            get {
                return ResourceManager.GetString("add_user", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO `wordknowledge` (`ID_Word_Front`, `ID_Word_Back`, `ID_User`, `Knowledge`) VALUES.
        /// </summary>
        internal static string add_word_knowledge {
            get {
                return ResourceManager.GetString("add_word_knowledge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM deck.
        /// </summary>
        internal static string all_decks {
            get {
                return ResourceManager.GetString("all_decks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM flipcardknowledge.
        /// </summary>
        internal static string all_flip_card_knowledge {
            get {
                return ResourceManager.GetString("all_flip_card_knowledge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM flipcard.
        /// </summary>
        internal static string all_flip_cards {
            get {
                return ResourceManager.GetString("all_flip_cards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM languages.
        /// </summary>
        internal static string all_langs {
            get {
                return ResourceManager.GetString("all_langs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM users.
        /// </summary>
        internal static string all_users {
            get {
                return ResourceManager.GetString("all_users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM wordknowledge.
        /// </summary>
        internal static string all_word_knowledge {
            get {
                return ResourceManager.GetString("all_word_knowledge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SELECT * FROM word.
        /// </summary>
        internal static string all_words {
            get {
                return ResourceManager.GetString("all_words", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string edit_flip_card {
            get {
                return ResourceManager.GetString("edit_flip_card", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string edit_flip_card_knowledge {
            get {
                return ResourceManager.GetString("edit_flip_card_knowledge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string edit_word_knowledge {
            get {
                return ResourceManager.GetString("edit_word_knowledge", resourceCulture);
            }
        }
    }
}
