//------------------------------------------------------------------------------
// <auto-generated>
//     Ten kod został wygenerowany przez narzędzie.
//     Wersja wykonawcza:4.0.30319.42000
//
//     Zmiany w tym pliku mogą spowodować nieprawidłowe zachowanie i zostaną utracone, jeśli
//     kod zostanie ponownie wygenerowany.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlashCards.Properties {
    using System;
    
    
    /// <summary>
    ///   Klasa zasobu wymagająca zdefiniowania typu do wyszukiwania zlokalizowanych ciągów itd.
    /// </summary>
    // Ta klasa została automatycznie wygenerowana za pomocą klasy StronglyTypedResourceBuilder
    // przez narzędzie, takie jak ResGen lub Visual Studio.
    // Aby dodać lub usunąć składową, edytuj plik ResX, a następnie ponownie uruchom narzędzie ResGen
    // z opcją /str lub ponownie utwórz projekt VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        /// Zwraca buforowane wystąpienie ResourceManager używane przez tę klasę.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FlashCards.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Przesłania właściwość CurrentUICulture bieżącego wątku dla wszystkich
        ///   przypadków przeszukiwania zasobów za pomocą tej klasy zasobów wymagającej zdefiniowania typu.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu INSERT INTO `deck` (`DeckName`) VALUES.
        /// </summary>
        internal static string add_deck {
            get {
                return ResourceManager.GetString("add_deck", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu INSERT INTO `flipcard` (`FrontContent`, `BackContent`, `ID_Deck`) VALUES.
        /// </summary>
        internal static string add_flip_card {
            get {
                return ResourceManager.GetString("add_flip_card", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu INSERT INTO `flipcardknowledge` (`ID_User`, `ID_FlipCard`, `Knowledge`) VALUES.
        /// </summary>
        internal static string add_flip_card_knowledge {
            get {
                return ResourceManager.GetString("add_flip_card_knowledge", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu INSERT INTO `users` (`Name`, `Surname`) VALUES.
        /// </summary>
        internal static string add_user {
            get {
                return ResourceManager.GetString("add_user", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu INSERT INTO `wordknowledge` (`ID_Word_Front`, `ID_Word_Back`, `ID_User`, `Knowledge`) VALUES.
        /// </summary>
        internal static string add_word_knowledge {
            get {
                return ResourceManager.GetString("add_word_knowledge", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu SELECT * FROM deck.
        /// </summary>
        internal static string all_decks {
            get {
                return ResourceManager.GetString("all_decks", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu SELECT * FROM flipcardknowledge.
        /// </summary>
        internal static string all_flip_card_knowledge {
            get {
                return ResourceManager.GetString("all_flip_card_knowledge", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu SELECT * FROM flipcard.
        /// </summary>
        internal static string all_flip_cards {
            get {
                return ResourceManager.GetString("all_flip_cards", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu SELECT * FROM languages.
        /// </summary>
        internal static string all_langs {
            get {
                return ResourceManager.GetString("all_langs", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu SELECT * FROM users.
        /// </summary>
        internal static string all_users {
            get {
                return ResourceManager.GetString("all_users", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu SELECT * FROM wordknowledge.
        /// </summary>
        internal static string all_word_knowledge {
            get {
                return ResourceManager.GetString("all_word_knowledge", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu SELECT * FROM word.
        /// </summary>
        internal static string all_words {
            get {
                return ResourceManager.GetString("all_words", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu DELETE FROM `deck` WHERE ID=.
        /// </summary>
        internal static string delete_deck {
            get {
                return ResourceManager.GetString("delete_deck", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu DELETE FROM `flipcard` WHERE ID=.
        /// </summary>
        internal static string delete_flipCard {
            get {
                return ResourceManager.GetString("delete_flipCard", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu DELETE FROM `flipcardknowledge` WHERE ID=.
        /// </summary>
        internal static string delete_flipCard_knowledge {
            get {
                return ResourceManager.GetString("delete_flipCard_knowledge", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu .
        /// </summary>
        internal static string edit_flip_card {
            get {
                return ResourceManager.GetString("edit_flip_card", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu .
        /// </summary>
        internal static string edit_flip_card_knowledge {
            get {
                return ResourceManager.GetString("edit_flip_card_knowledge", resourceCulture);
            }
        }
        
        /// <summary>
        /// Wyszukuje zlokalizowany ciąg podobny do ciągu .
        /// </summary>
        internal static string edit_word_knowledge {
            get {
                return ResourceManager.GetString("edit_word_knowledge", resourceCulture);
            }
        }
    }
}
